### PR TITLE
Preparing February agenda

### PR DESCRIPTION
**Pull request by AngelOnFira**
Preparing the February CTCFT agenda :slightly_smiling_face: 

So far, the schedule looks like this:

- (5 min) Opening remarks
- (20 min) Rust 2021 Survey Results #13 (@nrc) :heavy_check_mark: 
- (20 min) Async working group update #15 (@tmandry) :question: 
- (20 min) Compiler team ambitions #23 (@pnkfelix, @wesleywiser) :heavy_check_mark:

### CODE REVIEW

**Comment by AngelOnFira** [comment]
It seems that any commits automatically push to production :sweat_smile: I'm going to change that so it's only pushes to main

**Comment by AngelOnFira** [comment]
@nrc, @pnkfelix / @wesleywiser would it be possible to get a small description of your talks that I can add to the agenda?

**Comment by nrc** [comment]
"Nick will summarise the results of the survey, highlight findings which might be of interest to Rust teams, and outline how teams can request more in-depth analysis."

**Comment by AngelOnFira** [comment]
Since the Inside Rust blog just went out, I'm going to merge this, but if we get a description for the Compiler ambitions talk, I'll get that in as well :+1:

**Pull request merged**
